# Generated by Django 5.0.2 on 2026-04-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('end_time', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('free', 'Libre'), ('booked', 'Réservé')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(limit_choices_to={'role': 'lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('duration', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payé'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('missed', 'Absent')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_room_url', models.URLField(blank=True, null=True, verbose_name='Lien visio')),
                ('client_notes', models.TextField(blank=True, max_length=500, verbose_name='Notes client')),
                ('cancellation_reason', models.TextField(blank=True, max_length=500, verbose_name='Raison annulation')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(limit_choices_to={'role': 'lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_appointments', to=settings.AUTH_USER_MODEL)),
                ('availability', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='bookings.availability')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['lawyer', 'start_time'], name='bookings_av_lawyer__326a55_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['start_time', 'status'], name='bookings_av_start_t_4da4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['lawyer', 'status'], name='bookings_ap_lawyer__443038_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'status'], name='bookings_ap_client__6a70ab_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_time', 'status'], name='bookings_ap_start_t_d0ba26_idx'),
        ),
    ]
